// src/routes/character-creation/AncestryPointsCounter.tsx
import React from 'react';
import styled from 'styled-components';
import { useCharacter } from '../../lib/stores/characterContext';

const StyledContainer = styled.div`
  padding: 1.5rem;
  border: 2px solid #8b5cf6;
  border-radius: 12px;
  background: linear-gradient(135deg, #1e1b4b 0%, #312e81 100%);
  margin-bottom: 1rem;
  box-shadow: 0 8px 32px rgba(139, 92, 246, 0.3);
  text-align: center;
`;

const StyledTitle = styled.h2`
  margin: 0;
  color: #fbbf24;
  font-size: 1.8rem;
  font-weight: bold;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
  letter-spacing: 1px;
`;

function AncestryPointsCounter() {
  const { ancestryPointsRemaining } = useCharacter();

  return (
    <StyledContainer>
      <StyledTitle>Ancestry Points: {ancestryPointsRemaining}</StyledTitle>
    </StyledContainer>
  );
}

export default AncestryPointsCounter;

// src/routes/character-creation/AncestryPointsCounter.svelte
<script lang="ts">
  import { ancestryPointsRemaining } from '../../lib/stores/characterInProgressStore.ts';
</script>

<div class="points-counter">
  <h2>Ancestry Points: {$ancestryPointsRemaining}</h2>
</div>

<style>
  .points-counter {
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-bottom: 1rem;
  }
</style>
