// src/routes/character-creation/SelectedAncestries.svelte
<script lang="ts">
  import { characterInProgressStore } from '../../lib/stores/characterInProgressStore.ts';
  import { ancestriesData } from '../../lib/rulesdata/ancestries.ts';
  import { traitsData } from '../../lib/rulesdata/traits.ts';
  import type { IAncestry, ITrait } from '../../lib/rulesdata/types.ts';
  import { onDestroy } from 'svelte';

  let selectedAncestry1: IAncestry | undefined;
  let selectedAncestry2: IAncestry | undefined;
  let selectedTraits: string[] = [];

  const unsubscribe = characterInProgressStore.subscribe(store => {
    selectedAncestry1 = ancestriesData.find(a => a.id === store.ancestry1Id);
    selectedAncestry2 = ancestriesData.find(a => a.id === store.ancestry2Id);
    selectedTraits = JSON.parse(store.selectedTraitIds || '[]');
  });

  onDestroy(unsubscribe);

  function getTrait(traitId: string): ITrait | undefined {
    return traitsData.find(t => t.id === traitId);
  }

  function handleToggleTrait(traitId: string) {
    characterInProgressStore.update(store => {
      let currentTraits: string[] = JSON.parse(store.selectedTraitIds || '[]');
      const trait = getTrait(traitId);
      if (!trait) return store;

      if (currentTraits.includes(traitId)) {
        // Deselect
        currentTraits = currentTraits.filter(id => id !== traitId);
      } else {
        // Select
        currentTraits.push(traitId);
      }
      store.selectedTraitIds = JSON.stringify(currentTraits);
      return store;
    });
  }
</script>

<div class="selected-ancestries">
  {#if selectedAncestry1}
    <div class="ancestry-details">
      <h2>{selectedAncestry1.name}</h2>
      <h3>Default Traits</h3>
      <ul>
        {#each selectedAncestry1.defaultTraitIds || [] as traitId}
          {@const trait = getTrait(traitId)}
          {#if trait}
            <li>
              <label>
                <input type="checkbox" checked={selectedTraits.includes(traitId)} on:change={() => handleToggleTrait(traitId)} />
                {trait.name} ({trait.cost} pts) - {trait.description}
              </label>
            </li>
          {/if}
        {/each}
      </ul>
      <h3>Expanded Traits</h3>
      <ul>
        {#each selectedAncestry1.expandedTraitIds || [] as traitId}
          {@const trait = getTrait(traitId)}
          {#if trait}
            <li>
              <label>
                <input type="checkbox" checked={selectedTraits.includes(traitId)} on:change={() => handleToggleTrait(traitId)} />
                {trait.name} ({trait.cost} pts) - {trait.description}
              </label>
            </li>
          {/if}
        {/each}
      </ul>
    </div>
  {/if}
  {#if selectedAncestry2}
    <div class="ancestry-details">
      <h2>{selectedAncestry2.name}</h2>
      <h3>Default Traits</h3>
      <ul>
        {#each selectedAncestry2.defaultTraitIds || [] as traitId}
          {@const trait = getTrait(traitId)}
          {#if trait}
            <li>
              <label>
                <input type="checkbox" checked={selectedTraits.includes(traitId)} on:change={() => handleToggleTrait(traitId)} />
                {trait.name} ({trait.cost} pts) - {trait.description}
              </label>
            </li>
          {/if}
        {/each}
      </ul>
      <h3>Expanded Traits</h3>
      <ul>
        {#each selectedAncestry2.expandedTraitIds || [] as traitId}
          {@const trait = getTrait(traitId)}
          {#if trait}
            <li>
              <label>
                <input type="checkbox" checked={selectedTraits.includes(traitId)} on:change={() => handleToggleTrait(traitId)} />
                {trait.name} ({trait.cost} pts) - {trait.description}
              </label>
            </li>
          {/if}
        {/each}
      </ul>
    </div>
  {/if}
</div>

<style>
  .selected-ancestries {
    display: flex;
    gap: 2rem;
  }
  .ancestry-details {
    flex: 1;
  }
</style>

// src/routes/character-creation/SelectedAncestries.tsx
import React from 'react';
import { useCharacter } from '../../lib/stores/characterContext';
import { ancestriesData } from '../../lib/rulesdata/ancestries';
import { traitsData } from '../../lib/rulesdata/traits';
import type { IAncestry, ITrait } from '../../lib/rulesdata/types';
import {
  StyledOuterContainer,
  StyledMainTitle,
  StyledContainer,
  StyledAncestryDetails,
  StyledTitle,
  StyledSubtitle,
  StyledList,
  StyledListItem,
  StyledLabel,
  StyledCheckbox
} from './styles/SelectedAncestries.styles';

function SelectedAncestries() {
  const { state, dispatch } = useCharacter();
  
  const selectedAncestry1 = ancestriesData.find(a => a.id === state.ancestry1Id);
  const selectedAncestry2 = ancestriesData.find(a => a.id === state.ancestry2Id);
  const selectedTraits: string[] = JSON.parse(state.selectedTraitIds || '[]');

  function getTrait(traitId: string): ITrait | undefined {
    return traitsData.find(t => t.id === traitId);
  }

  function handleToggleTrait(traitId: string) {
    const trait = getTrait(traitId);
    if (!trait) return;

    let currentTraits = [...selectedTraits];
    
    if (currentTraits.includes(traitId)) {
      // Deselect
      currentTraits = currentTraits.filter(id => id !== traitId);
    } else {
      // Select
      currentTraits.push(traitId);
    }
    
    dispatch({ type: 'SET_TRAITS', selectedTraitIds: JSON.stringify(currentTraits) });
  }

  function renderAncestryTraits(ancestry: IAncestry) {
    return (
      <StyledAncestryDetails>
        <StyledTitle>{ancestry.name}</StyledTitle>
        
        <StyledSubtitle>Default Traits</StyledSubtitle>
        <StyledList>
          {(ancestry.defaultTraitIds || []).map(traitId => {
            const trait = getTrait(traitId);
            if (!trait) return null;
            return (
              <StyledListItem key={traitId}>
                <StyledLabel>
                  <StyledCheckbox 
                    type="checkbox" 
                    checked={selectedTraits.includes(traitId)} 
                    onChange={() => handleToggleTrait(traitId)} 
                  />
                  {trait.name} ({trait.cost} pts) - {trait.description}
                </StyledLabel>
              </StyledListItem>
            );
          })}
        </StyledList>
        
        <StyledSubtitle>Expanded Traits</StyledSubtitle>
        <StyledList>
          {(ancestry.expandedTraitIds || []).map(traitId => {
            const trait = getTrait(traitId);
            if (!trait) return null;
            return (
              <StyledListItem key={traitId}>
                <StyledLabel>
                  <StyledCheckbox 
                    type="checkbox" 
                    checked={selectedTraits.includes(traitId)} 
                    onChange={() => handleToggleTrait(traitId)} 
                  />
                  {trait.name} ({trait.cost} pts) - {trait.description}
                </StyledLabel>
              </StyledListItem>
            );
          })}
        </StyledList>
      </StyledAncestryDetails>
    );
  }

  return (
    <StyledOuterContainer>
      <StyledMainTitle>Ancestry Traits</StyledMainTitle>
      <StyledContainer>
        {selectedAncestry1 && renderAncestryTraits(selectedAncestry1)}
        {selectedAncestry2 && renderAncestryTraits(selectedAncestry2)}
      </StyledContainer>
    </StyledOuterContainer>
  );
}

export default SelectedAncestries;
